services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: gsm_news
      POSTGRES_USER: gsm_user
      POSTGRES_PASSWORD: gsm_pass_123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gsm_user -d gsm_news"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
